language: node_js

node_js: 
  - "10.6.0"

install:
  - npm install codecov
  
before_script:
  - npm run build
  - npm test

after_success:
  - codecov --token=$CODECOV_TOKEN

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  target-branch: gh-pages
  on:
    branch: master
